### ISSUE TITLE
FYI, you may have to re-record cassettes with psych 2.1.0+

### ISSUE THREAD

**Issue by jerryk55** [ManageIQ/manageiq-smartstate#58]
See https://github.com/ghempton/camcorder/issues/13

**Comment by mfeifer** [comment]
@jerryk55 is this still an issue?

**Comment by jerryk55** [comment]
@mfeifer this is a "CYA" issue - its a warning... Not sure why it would not still be applicable, and not sure where else we would track it.

**Comment by mfeifer** [comment]
@Fryguy set this to "help wanted"?

**Comment by Fryguy** [comment]
Sounds like we can just close it and if it's actually an issue then the VCRs will fail.
